# Generated by Django 5.1.6 on 2025-03-12 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_type', models.CharField(choices=[('D', '顕性het'), ('D2', '顕性homo'), ('C', '共顕性het'), ('C2', '共顕性homo'), ('R2', '潜性homo'), ('R', '潜性het'), ('-2', 'ワイルドhomo'), ('-', 'ワイルドhet'), ('N', 'no_name')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('morph_name', models.CharField(max_length=100)),
                ('morph_detail', models.TextField(blank=True, null=True)),
                ('gene_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morph.gene')),
            ],
        ),
        migrations.CreateModel(
            name='ComboMorph',
            fields=[
                ('combo_morph_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('morphs', models.ManyToManyField(to='morph.morph')),
            ],
        ),
    ]
