# Generated by Django 5.1.6 on 2025-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='morph_detail',
            field=models.TextField(null=True),
        ),
    ]
