# Generated by Django 5.1.6 on 2025-02-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0002_alter_morph_morph_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='morph_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
