# Generated by Django 5.1.6 on 2025-02-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0003_alter_morph_morph_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(choices=[('D', '顕性het'), ('D2', '顕性homo'), ('C', '共顕性het'), ('C2', '共顕性homo'), ('R', '潜性')], max_length=3),
        ),
    ]
