# Generated by Django 5.1.6 on 2025-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0004_alter_gene_gene_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboMorph',
            fields=[
                ('combo_morph_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('morphs', models.ManyToManyField(to='morph.morph')),
            ],
        ),
    ]
