# Generated by Django 5.1.6 on 2025-02-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0005_combomorph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(choices=[('D', '顕性het'), ('D2', '顕性homo'), ('C', '共顕性het'), ('C2', '共顕性homo'), ('R2', '潜性'), ('R', '潜性het')], max_length=3),
        ),
    ]
