# Generated by Django 5.1.6 on 2025-03-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0008_alter_gene_gene_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(choices=[('D', '顕性het'), ('D2', '顕性homo'), ('C', '共顕性het'), ('C2', '共顕性homo'), ('R2', '潜性homo'), ('R', '潜性het'), ('-2', 'ワイルドhomo'), ('-', 'ワイルドhet'), ('N', 'no_name')], max_length=10),
        ),
    ]
