# Generated by Django 5.1.6 on 2025-03-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0009_alter_gene_gene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
