# Generated by Django 5.1.6 on 2025-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0010_morph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morph',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='morph',
            name='morph_name',
            field=models.CharField(max_length=100),
        ),
    ]
